name: Manually triggered yocto build
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get install -y \
            build-essential \
            chrpath \
            diffstat \
            gawk \
            libncurses5-dev \
            python3-distutils \
            texinfo \
            liblz4-tool

  fetch-yocto:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - run: |
          git clone -b honister git://git.yoctoproject.org/poky.git poky-honister

  setup-env:
    runs-on: ubuntu-latest
    needs: fetch-yocto
    steps:
      - run: |
          cd poky-honister
          source oe-init-build-env

  build:
    runs-on: ubuntu-latest
    needs: setup-env
    steps:
      - run: |
          bitbake core-image-minimal
