name: Manually triggered yocto build
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          sudo apt-get install -y \
            build-essential \
            chrpath \
            diffstat \
            gawk \
            libncurses5-dev \
            python3-distutils \
            texinfo \
            liblz4-tool

      - name: fetch-yocto
        run: |
          git clone -b honister git://git.yoctoproject.org/poky.git poky-honister

      - name: setup-env
        run: |
          cd poky-honister
          sudo source oe-init-build-env
      
      - name: compile
        run: |
          bitbake core-image-minimal
